### ISSUE TITLE
1.15: cant insert with optional :conflict param

### ISSUE THREAD

**Issue by nightshade427** [orthecreedence/cl-rethinkdb#33]
If I try and call update with optional param :conflict I get an error:
```lisp
 "Query failed to compile (NIL): Unrecognized optional argument `conflict`.\n---\n#<REQL-CMD INSERT/56 (#<CL-RETHINKDB-REQL::REQL-CMD\n                        TABLE/15 (\"database___websites\") {} {100B391C83}>\n                      #<HASH-TABLE :TEST EQL :COUNT 10 {100B389783}>) {\"conflict\":\"update\",\"durability\":\"soft\"} {100B392993}>"
```

**Comment by orthecreedence** [comment]
Odd, getting the same. I wonder if this was put into the 1.15 protocol spec but not supported server-side? I might be upgrading this to 1.16 soon anyway.

**Comment by nightshade427** [comment]
Okay, let me know and I will test out ;)

**Comment by nightshade427** [comment]
Were you able to upgrade to 1.16 and see if issue went away?

**Comment by nightshade427** [comment]
I will update here shortly and see :)

**Comment by orthecreedence** [comment]
I'm working on a 1.16 branch (started last night). I got the new commands in and everything, but having trouble testing because I can't compile 1.16 (see https://github.com/rethinkdb/rethinkdb/issues/3956). If 2.0 is coming out soon, I might just write the latest version against that (if you don't object) and skip having to upgrade in a month anyway.

One thing that may not make it in immediately are changefeeds. I think I have all the parsing done for them already, but there's no interface or logic for handling them. I want to get any changes to the protocol solidified and then work on changefeeds after.

In the meantime, I actually don't think it would be a problem for you to run the current cl-rethinkdb against Rethinkdb 1.16 (they use the same protocol versions, but v1.16 just has more commands). I could be wrong, but try giving it a shot. If that's the case, then I'd like to save efforts and focus on 2.0. I've been flaky lately with how much time I can devote to my libraries, so I'd rather maximize efficiency =].

**Comment by nightshade427** [comment]
I am already running cl-rethink master against rethink 1.16.2. I havent had a chance to add back in the :conflict param and test yet. I will do that shortly and report back if it is still issue. ;)

**Comment by nightshade427** [comment]
Sorry for the delay, going to test latest master with rethink 1.16.2 and the conflict parameter. Will let you know how it goes.

**Comment by nightshade427** [comment]
Totally works in 1.16.2 rethinkdb ;)
